AMI_USERNAME = "Portero"
AMI_PASSWORD = "PorteroPassword"
DEVICE_PATH = "/dev/input/event0"
DOORPHONE_CALLER_ID = "Doorphone"
DOORPHONE_EXTENSION = "800"
ORIGINATE_CONTEXT = "from-internal"
SERVER_IP = "127.0.0.1"
SERVER_PORT = 5038
